### ISSUE TITLE
Playing a vorbis file fails with "invalid argument"

### ISSUE THREAD

**Issue by siimphh** [jfreymuth/vorbis#5]
I'm using the library indirectly through github.com/hajimehoshi/ebiten and playing a vorbis file there fails with "invalid argument". I haven't done any digging yet to try to figure out what's going on (and I don't know internals of either library yet, so will take some time).

FWIW, the failure happens ever so slightly before the very end of the audio is played, so possibly something with the end of the file. The file itself was just a recording saved with audacity so shouldn't be anything special.

**Comment by siimphh** [comment]
Seems I can't attach .ogg files, so here's a link:

https://p6drad-teel.net/~windo/tmp/recap_1.ogg

**Comment by siimphh** [comment]
I tried just decoding the file directly with oggvorbis and that worked fine. I'll try to see if this is something specific to what ebiten is doing that is causing a problem.

**Comment by siimphh** [comment]
I now think this is a problem in ebiten and not with vorbis.

**Comment by hajimehoshi** [comment]
Should we close this? :-)
